2019-08-30 10:07:36,626 ERROR: Exception on /login [GET] [in D:\Program Files\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PythonProject\flask_microblog\app\routes.py", line 78, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PythonProject\flask_microblog\app\templates\base.html", line 54, in template
    {% block content %}{% endblock %}
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "D:\PythonProject\flask_microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PythonProject\flask_microblog\app\templates\base.html", line 54, in template
    {% block content %}{% endblock %}
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 543, in _generate
    optimized=self.optimized)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\compiler.py", line 82, in generate
    generator.visit(node)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2019-08-30 10:07:36,661 ERROR: Exception on /login [GET] [in D:\Program Files\Anaconda3\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\PythonProject\flask_microblog\app\routes.py", line 78, in login
    return render_template('login.html', title='Sign In', form=form)
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "D:\Program Files\Anaconda3\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PythonProject\flask_microblog\app\templates\base.html", line 54, in template
    {% block content %}{% endblock %}
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "D:\PythonProject\flask_microblog\app\templates\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "D:\PythonProject\flask_microblog\app\templates\base.html", line 54, in template
    {% block content %}{% endblock %}
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\environment.py", line 543, in _generate
    optimized=self.optimized)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\compiler.py", line 82, in generate
    generator.visit(node)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\visitor.py", line 38, in visit
    return f(node, *args, **kwargs)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\compiler.py", line 718, in visit_Template
    self.fail('block %r defined twice' % block.name, block.lineno)
  File "D:\Program Files\Anaconda3\lib\site-packages\jinja2\compiler.py", line 315, in fail
    raise TemplateAssertionError(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateAssertionError: block 'content' defined twice
2019-08-30 10:09:28,922 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:09:30,112 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:09:47,393 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:09:50,107 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:09:51,572 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:23:56,408 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:23:57,763 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:29:08,630 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:29:10,591 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:37:14,523 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 10:37:16,075 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 11:03:42,010 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:43]
2019-08-30 11:03:43,277 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:43]
2019-08-30 11:16:08,237 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 11:16:09,554 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:41]
2019-08-30 14:16:21,820 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:45]
2019-08-30 14:24:48,419 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:50]
2019-08-30 14:24:49,905 INFO: Microblog startup [in D:\PythonProject\flask_microblog\app\__init__.py:50]
